plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\Desktop\\Baracoda\\pwa\\dist\\client"
publishOrigin = "ui"
commandOrigin = "ui"
command = "remix vite:build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]